kind: Deployment
apiVersion: apps/v1
metadata:
  name: nsd-tr-dns
  namespace: gokhanusta
  labels:
    app: nsd-tr-dns
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/alias-name: aliaaaaaas
    kubesphere.io/creator: gusta
    kubesphere.io/description: 'bu alan description alanı bu alanana bilgi yaz. :))'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsd-tr-dns
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nsd-tr-dns
    spec:
      containers:
        - name: container-xdofr4
          image: 'hrb.usom.gov.tr/external/nsd:tekton'
          ports:
            - name: tcp-dns
              containerPort: 53
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1200Mi
            requests:
              cpu: 520m
              memory: 880Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumes:
          - name: workdir1
            hostPath:
                path: /var/log/pods

        - name: container-v4u0bi
          image: 'hrb.usom.gov.tr/external/nsd_external:master'
          ports:
            - name: http-ss
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 930m
              memory: 1350Mi
            requests:
              cpu: 510m
              memory: 1100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600